"""initial schema

Revision ID: 53f83f674cc8
Revises: 
Create Date: 2026-09-06 23:43:48.173336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f83f674cc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_runs',
    sa.Column('run_id', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('dataset_name', sa.String(length=255), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('rows_processed', sa.Integer(), nullable=False),
    sa.Column('rows_flagged', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_quality_runs_dataset_name'), 'quality_runs', ['dataset_name'], unique=False)
    op.create_table('data_lineage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transformations_applied', sa.JSON(), nullable=False),
    sa.Column('destination_table', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['quality_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('source_run_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['source_run_id'], ['quality_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_rows_source_run_id'), 'dataset_rows', ['source_run_id'], unique=False)
    op.create_table('quality_issues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=16), nullable=False),
    sa.Column('row_reference', sa.String(length=64), nullable=False),
    sa.Column('column', sa.String(length=64), nullable=False),
    sa.Column('issue_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['quality_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_issues_issue_type'), 'quality_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_quality_issues_run_id'), 'quality_issues', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_issues_run_id'), table_name='quality_issues')
    op.drop_index(op.f('ix_quality_issues_issue_type'), table_name='quality_issues')
    op.drop_table('quality_issues')
    op.drop_index(op.f('ix_dataset_rows_source_run_id'), table_name='dataset_rows')
    op.drop_table('dataset_rows')
    op.drop_table('data_lineage')
    op.drop_index(op.f('ix_quality_runs_dataset_name'), table_name='quality_runs')
    op.drop_table('quality_runs')
    # ### end Alembic commands ###
